### ISSUE TITLE
Wrong timing for scopes

### ISSUE THREAD

**Issue by akaStiX** [jonasmr/microprofile#38]
While integrating microprofile into our engine I've noticed that some scopes have wrong timing.
For example we synchronize render and update threads with event - update thread waits on render thread to signal after it's done with rendering. After that update thread sends a message to render thread to update profiler and call MicroprofileFlip. It's demonstrated on [screenshot](https://imgur.com/a/en1P6RB). You can clearly see that Flip is displayed at least 0.5ms before it's even called!
While investigating this issue I added a few Sleep(1) here and there and then I've noticed that our jobs were misplaced by roughly 1ms - render thread spawns jobs and then waits on them, however profiler output shows that wait has finished even before worker threads started executing any jobs.
So I suspect Sleep somehow interferes.
Any pointers?

**Comment by jonasmr** [comment]
Hi.

I'm inclined to think that the timing in microprofile is correct: Mostly because I've used it for a long while without experiencing something like you report, and also you're the first to report this problem - Noone else has complained about it being of.

As for the picture - It does not really show anything - without seeing the code its impossible to see if it is correct or not.

With that said, it is of course possible that there is a bug there - If you can make a simple program that I can run to reproduce the error, I could take a look at it. 

You mention that you synchronize two threads with an event: You could make a -very- simple emultation of your program you have two threads that have the same events, but just Sleep instead of doing real work.
